CREATE DATABASE session2_bai1;
USE session2_bai1;

CREATE TABLE Products (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    ProductName VARCHAR(150) NOT NULL,
    Price DECIMAL(19, 4) NOT NULL CHECK (Price >= 0),
    Description VARCHAR(5000),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);