CREATE DATABASE session2_bai2;
USE session2_bai2;

CREATE TABLE CUSTOMERS (
    CustomerID INT PRIMARY KEY,
    FullName VARCHAR(100),
    Email VARCHAR(100),
    Age INT
);

ALTER TABLE CUSTOMERS 
MODIFY COLUMN CustomerID INT AUTO_INCREMENT;

ALTER TABLE CUSTOMERS 
MODIFY COLUMN FullName VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS 
MODIFY COLUMN Email VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS 
ADD CONSTRAINT UC_Email UNIQUE (Email);

ALTER TABLE CUSTOMERS 
ADD CONSTRAINT CHK_Age CHECK (Age >= 0 AND Age <= 120);